name: Build TWRP

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup and Initialize
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          export PATH=~/bin:$PATH
          mkdir workspace
          cd workspace
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc)
          
          # Переносим дерево устройства СРАЗУ ПОСЛЕ repo sync, пока мы в workspace
          mkdir -p device/xiaomi/frost
          # Копируем всё из корня репозитория (который сейчас в $GITHUB_WORKSPACE) в workspace/device/xiaomi/frost
          cp -r $GITHUB_WORKSPACE/* device/xiaomi/frost/
          # Удаляем лишние папки, чтобы не было дублей
          rm -rf device/xiaomi/frost/workspace
          rm -rf device/xiaomi/frost/.git
          rm -rf device/xiaomi/frost/.github

      - name: Build
        run: |
          cd workspace
          source build/envsetup.sh
          lunch twrp_frost-eng
          mka recoveryimage
