name: Building TWRP

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
  DEVICE: frost
  DT_LINK: https://github.com/Linzixrxq/android_device_xiaomi_frost
  DT_BRANCH: twrp-11
  DT_PATH: device/xiaomi/frost
  TARGET: bootimage
  TZ: Asia/Manila

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Check Out Workflow
      uses: actions/checkout@v4

    - name: Cleanup Space
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare Build Environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install gperf gcc-multilib g++-multilib libc6-dev x11proto-core-dev libx11-dev tree lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache liblz4-tool libncurses-dev libsdl1.2-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev python3
        git config --global user.name "Linzixrxq"
        git config --global user.email "action@github.com"

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install Repo Tool
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Sync TWRP Source
      run: |
        PATH=~/bin:$PATH
        mkdir twrp
        cd twrp
        repo init -u $MANIFEST --depth=1
        repo sync -c -j8 --force-sync --no-clone-bundle --no-tags
        rm -rf .repo

    - name: Checkout Device Tree
      run: |
        git clone https://github.com/Linzixrxq/android_device_xiaomi_frost twrp/device/xiaomi/frost

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Build TWRP Boot Image
      run: |
        PATH=~/bin:$PATH
        cd twrp
        export ALLOW_MISSING_DEPENDENCIES=true && source build/envsetup.sh && lunch twrp_frost-eng && mka $TARGET -j$(nproc --all)
        cp out/target/product/frost/boot.img out/target/product/frost/boot-frost-A11-$(date +"%Y%m%d").img  

    - name: Release TWRP Image
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: Poco_C40-frost-${{ github.run_id }}
        name: TWRP 3.7.x Android 11 (Frost)
        files: |
          twrp/out/target/product/frost/*boot*.img
